defaults:
  credentials: e2e
pipeline:
  deploy:
    action: gcp/cloudfunctions:deploy
    '@name': Transfer
    entryPoint: TransferFn
    runtime: go111
    vpcConnector: projects/${gcp.projectId}/locations/us-central1/connectors/myConnector
    source:
      URL: $WorkingDirectory('.')
